codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        # basic
        target: 80%
        threshold: 2%
        # advanced
        if_ci_failed: error
        only_pulls: true
    patch:
      default:
        # basic
        target: 80%
        threshold: 2%
        # advanced
        if_ci_failed: error
        only_pulls: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no